#ifndef COMPONENT_TYPES_H
#define COMPONENT_TYPES_H

///Enum
enum ComponentType
{
    COMPONENT_NONE = 0,
    COMPONENT_PROTOTYPE = 1,
    COMPONENT_POSITION = 2,
    COMPONENT_VELOCITY = 4,
    COMPONENT_HITBOX = 8,
    COMPONENT_SPRITE = 16,
    COMPONENT_INPUT = 32,
    COMPONENT_PLAYER = 64,
    COMPONENT_END
};

#endif
